pose_landmark_id = {
    "RIGHT_WRIST" : 16,
    "LEFT_WRIST" : 15,
    "RIGHT_SHOULDER" : 12,
    "LEFT_SHOULDER" : 11,
    "RIGHT_ELBOW" : 14,
    "LEFT_ELBOW" : 13,
    "RIGHT_HIP" : 24,
    "LEFT_HIP" : 23,
    "RIGHT_KNEE" : 26,
    "LEFT_KNEE" : 25,
    "RIGHT_HEEL" : 30,
    "LEFT_HEEL" : 29,
  "NOSE" : 0,
  "LEFT_EYE_INNER" : 1,
  "LEFT_EYE" : 2,
  "LEFT_EYE_OUTER" : 3,
  "RIGHT_EYE_INNER" : 4,
  "RIGHT_EYE" : 5,
  "RIGHT_EYE_OUTER" : 6,
  "LEFT_EAR" : 7,
  "RIGHT_EAR" : 8,
  "MOUTH_LEFT" : 9,
  "MOUTH_RIGHT" : 10,
  "LEFT_PINKY" : 17,
  "RIGHT_PINKY" : 18,
  "LEFT_INDEX" : 19,
  "RIGHT_INDEX" : 20,
  "LEFT_THUMB" : 21,
  "RIGHT_THUMB" : 22,
  "LEFT_ANKLE" : 27,
  "RIGHT_ANKLE" : 28,
  "LEFT_FOOT_INDEX" : 31,
  "RIGHT_FOOT_INDEX" : 32,}


landmark_names = [
        'nose',
        'left_eye_inner', 'left_eye', 'left_eye_outer',
        'right_eye_inner', 'right_eye', 'right_eye_outer',
        'left_ear', 'right_ear',
        'mouth_left', 'mouth_right',
        'left_shoulder', 'right_shoulder',
        'left_elbow', 'right_elbow',
        'left_wrist', 'right_wrist',
        'left_pinky_1', 'right_pinky_1',
        'left_index_1', 'right_index_1',
        'left_thumb_2', 'right_thumb_2',
        'left_hip', 'right_hip',
        'left_knee', 'right_knee',
        'left_ankle', 'right_ankle',
        'left_heel', 'right_heel',
        'left_foot_index', 'right_foot_index',
    ]